### ISSUE TITLE
Cannot select layer to apply to

### ISSUE THREAD

**Issue by baidarkabob** [arc2qgis/qlyrx#6] opened 2021-03-23 20:15 UTC
Hi, I am unable to select the layer to apply the .lyrx file too. Drop-down is non-responsive. 

Windows 10 64 build 19041
QGIS 3.181
3840 x 2160 screen resolution

![Screenshot 2021-03-23 121137](https://user-images.githubusercontent.com/81263246/112211650-01d39000-8bd1-11eb-8fda-0c2882c4e868.png)

**Comment by bogind** [comment] 2021-06-17 12:23
Sorry for the long response time,
Has this worked for you since? 
Did you perhaps first open the plugin window and only then the layers?
Have you tried this with other versions of QGIS?

**Comment by mchisi** [comment] 2021-06-18 06:10
Hi,
I'm having the same Problem. I am using QGIS 3.16.4. Is this the issue?

**Comment by bogind** [comment] 2021-06-18 06:13
@mchisi 
What operating system are you using?
What version of the plugin?
Did you try reopening the plugin window after loading layers?
Are you getting an error message?

**Comment by mchisi** [comment] 2021-06-18 06:24
> @mchisi
> What operating system are you using?
> What version of the plugin?
> Did you try reopening the plugin window after loading layers?
> Are you getting an error message?

Windows 10 Enterprise and the Version of the plugin is 0.3. I installed it once from the Plugin-Directory on QGIS and once from the ZIP-File, no difference.

The Error message is in the Python console on QGIS is:
Traceback (most recent call last):
              File "C:/Users/vamch/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1525, in run
              geometry_general_type_str = self.generalise_geom_type(layer) if not isRaster else 'raster'
              File "C:/Users/vamch/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 406, in generalise_geom_type
              geometry_type_str = QgsWkbTypes.displayString(int(layer.wkbType()))
             AttributeError: 'NoneType' object has no attribute 'wkbType'
             
But I think this has to do with me not having selected a Layer (because I can't) and clicking OK anyway

**Comment by bogind** [comment] 2021-06-18 06:28
You can try release 0.3.1 (just added), I rewrote the layer loading part of the plugin which seemed to have stopped working in newer versions.
It should be available form the plugins repository in a few hours at most I hope, or just take it from the releases.
https://github.com/arc2qgis/qlyrx/releases/tag/v0.3.1

**Comment by bogind** [comment] 2021-06-18 07:02
@mchisi 
can you update if the new release fixed this issue for you?
reopening until I can confirm this works.

**Comment by mchisi** [comment] 2021-06-18 07:37
> @mchisi
> can you update if the new release fixed this issue for you?
> reopening until I can confirm this works.

Thank you so much! I did indeed work now with 0.3.1 yes :)

...I am having some issues with #Enable using differently named layers and fields #8 now but I will write there if I can't get them sorted.

Perfect support, thx again

**Comment by bogind** [comment] 2021-06-18 07:41
#8 is an issue I opened for the further development, I hope I'll have time to implement that soon enough (2-3 months).
Closing this issue as it's now resolved.

**Closed by bogind** 2021-06-18 07:41 UTC
